## Vectors

    A vector is an ordered set of numbers, often representing quantities that have both magnitude and direction. 
    In linear algebra, vectors are typically denoted as 
$ v = [v_1, v_2, …, v_n] $

where $v_1, v_2, …, v_n$ are the components of the vector.

    Vector Addition, Subtraction, and Scalar Multiplication:
    
    Addition: 
        Adding two vectors results in a new vector where each component is the sum of the corresponding components of the original vectors.
    
    Subtraction: 
        Subtracting one vector from another results in a new vector where each component is the difference between the corresponding components of the original vectors.
    
    Scalar Multiplication: 
        Multiplying a vector by a scalar involves multiplying each component of the vector by that scalar.

In [1]:
import numpy as np

# Define two vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Vector Addition
addition_result = v1 + v2

# Vector Subtraction
subtraction_result = v1 - v2

# Scalar Multiplication
scalar = 2
scalar_multiplication_result = scalar * v1

print("Vector Addition:", addition_result)
print("Vector Subtraction:", subtraction_result)
print("Scalar Multiplication:", scalar_multiplication_result)

Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]
Scalar Multiplication: [2 4 6]


    Inner Product and Dot Product:
    
    Inner Product: 
        The inner product of two vectors is the sum of the products of their corresponding components.
        
    Dot Product: 
        The dot product of two vectors is a specific type of inner product.

In [2]:
# Inner Product
inner_product_result = np.inner(v1, v2)

# Dot Product
dot_product_result = np.dot(v1, v2)

print("Inner Product:", inner_product_result)
print("Dot Product:", dot_product_result)

Inner Product: 32
Dot Product: 32


## Matrices:

    A matrix is a 2D array of numbers, symbols, or expressions arranged in rows and columns. 
    It is typically denoted as 
$ A = [a_{ij}]$, 

where $a_{ij}$ represents the element in the i-th row and j-th column.

    Matrix Addition, Subtraction, and Scalar Multiplication:
    
        Addition: 
            Adding two matrices results in a new matrix where each element is the sum of the corresponding elements of the original matrices.
        
        Subtraction: 
            Subtracting one matrix from another results in a new matrix where each element is the difference between the corresponding elements of the original matrices.
        
        Scalar Multiplication: 
            Multiplying a matrix by a scalar involves multiplying each element of the matrix by that scalar.

In [3]:
# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
matrix_addition_result = A + B

# Matrix Subtraction
matrix_subtraction_result = A - B

# Scalar Multiplication
scalar_multiplication_matrix_result = scalar * A

print("Matrix Addition:\n", matrix_addition_result)
print("Matrix Subtraction:\n", matrix_subtraction_result)
print("Scalar Multiplication:\n", scalar_multiplication_matrix_result)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Scalar Multiplication:
 [[2 4]
 [6 8]]


    Matrix Multiplication:
        Matrix multiplication is the process of multiplying two matrices to obtain a new matrix. 
        The number of columns in the first matrix must be equal to the number of rows in the second matrix for the multiplication to be defined.

In [4]:
# Matrix Multiplication
matrix_multiplication_result = np.matmul(A, B)

print("Matrix Multiplication:\n", matrix_multiplication_result)

Matrix Multiplication:
 [[19 22]
 [43 50]]


    Transposition and Symmetric Matrices:
        Transposition: 
            The transpose of a matrix is obtained by swapping its rows with columns.
        Symmetric Matrices: 
            A matrix is symmetric if it is equal to its transpose.

In [5]:
# Matrix Transposition
transposed_matrix = np.transpose(A)

# Symmetric Matrix
symmetric_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])

print("Transposed Matrix:\n", transposed_matrix)
print("Is Symmetric Matrix:", np.array_equal(symmetric_matrix, symmetric_matrix.T))

Transposed Matrix:
 [[1 3]
 [2 4]]
Is Symmetric Matrix: True


## Vector Spaces and Subspaces:

    Definition and Basis:
    A vector space is a set of vectors closed under addition and scalar multiplication. A subspace is a subset of a vector space that is itself a vector space.

In [6]:
# Vector Space and Subspace
vector_space = np.array([1, 2, 3])
subspace = np.array([1, 2])

# Check if subspace is a subset of vector_space
is_subspace = np.all(np.isin(subspace, vector_space))

print("Is Subspace:", is_subspace)

Is Subspace: True


## Orthogonality:
    Orthogonal Vectors and Subspaces:
        Vectors are orthogonal if their dot product is zero. 
        Subspaces are orthogonal if every vector in one subspace is orthogonal to every vector in the other.

In [7]:
# Orthogonal Vectors
v1 = np.array([2, -2, 0])
v3 = np.array([2, 2, 4])

# Check if v1 and v3 are orthogonal
are_orthogonal = np.dot(v1, v3) == 0

print("Are v1 and v3 Orthogonal:", are_orthogonal)

Are v1 and v3 Orthogonal: True
