    Matrix factorizations are essential techniques in linear algebra that represent a matrix as a product of other matrices.
    
    These factorizations have various applications in numerical algorithms, data analysis, and machine learning. 
    
    Here are a few important matrix factorizations:
    
### Singular Value Decomposition (SVD):
        Definition:
            SVD decomposes a matrix A into three matrices 
    where U and V are orthogonal matrices, and Σ is a diagonal matrix with singular values.
    
$$ A = U \Sigma V^T$$

In [1]:
import numpy as np

# Define a matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform SVD
U, Sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma matrix:\n", np.diag(Sigma))
print("Vt matrix:\n", Vt)

U matrix:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Sigma matrix:
 [[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]
Vt matrix:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


### LU Decomposition

    Definition:
        LU decomposition factorizes a matrix A into the product of a lower triangular matrix L and an upper triangular matrix U.       
$$ A = LU$$

In [3]:
import scipy
# Perform LU decomposition
P, L, U = scipy.linalg.lu(A)

print("P matrix (permutation matrix):\n", P)
print("L matrix (lower triangular matrix):\n", L)
print("U matrix (upper triangular matrix):\n", U)

P matrix (permutation matrix):
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L matrix (lower triangular matrix):
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
U matrix (upper triangular matrix):
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


### Cholesky Decomposition:

    Definition:
        Cholesky decomposition factorizes a symmetric positive definite matrix A into the product of a lower triangular matrix L and its transpose L.
$$ A = LL^T$$

In [4]:
# Check if the matrix A is symmetric positive definite
is_symmetric_positive_definite = np.all(np.linalg.eigvals(A) > 0)

if is_symmetric_positive_definite:
    # Perform Cholesky decomposition
    L = np.linalg.cholesky(A)

    print("L matrix (lower triangular matrix):\n", L)
else:
    print("Matrix A is not symmetric positive definite.")

Matrix A is not symmetric positive definite.
