# NumPy 
     It's important for numerical computations in Python is because it is designed for efficiency on large arrays of data.
     
     There are a number of reasons for this:
     
        • NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. 
        
        • NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [1]:
import numpy as np

# Array creation

## Conversion from other Python structures

    Lists and tuples are defined using [...] and (...), respectively.
    
    Can define ndarry creation.

In [2]:
array_1D = np.array([1, 2, 3, 4])

print(array_1D)

[1 2 3 4]


In [3]:
array_2D = np.array([[1, 2], [3, 4]])

print(array_2D)

[[1 2]
 [3 4]]


In [4]:
array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


    When you use 'numpy.array' to define a new array, you should consider the dtype of the elements in the array, which can be specified explicitly. 

## In-Built NumPy array creation functions

    numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [5]:
# 1D arrays
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(0, 10, 3, dtype = float)

array([0., 3., 6., 9.])

    numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)

In [8]:
np.linspace(1,10,4, dtype=int)

array([ 1,  4,  7, 10])

    numpy.eye(rows, columns=None, k(diagonal)=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
    
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [9]:
# 2D arrays
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

    numpy.diag(v, k=0)

In [11]:
np.diag(np.linspace(1,10,4))

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.],
       [ 0.,  0.,  7.,  0.],
       [ 0.,  0.,  0., 10.]])

In [12]:
np.diag(np.linspace(1,10,3), k=1)

array([[ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  5.5,  0. ],
       [ 0. ,  0. ,  0. , 10. ],
       [ 0. ,  0. ,  0. ,  0. ]])

In [13]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [14]:
# ndarrays

    numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

    numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [16]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Replicating, joining, or mutating existing arrays

    numpy.vstack(tup, *, dtype=None, casting='same_kind')
    
    Stack arrays in sequence vertically (row wise)

In [17]:
np.vstack((1,2,3,4,5), dtype= int)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

    numpy.hstack(tup, *, dtype=None, casting='same_kind')

In [19]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [20]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

    numpy.block(arrays)

    Assemble an nd-array from nested lists of blocks.

In [21]:
A = np.eye(2) * 2
B = np.eye(3) * 3

np.block([
    [A, np.zeros((2, 3))], 
    [np.zeros((3, 2)), B]
])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])