# NumPy 
     It's important for numerical computations in Python is because it is designed for efficiency on large arrays of data.
     
     There are a number of reasons for this:
     
        • NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. 
        
        • NumPy operations perform complex computations on entire arrays without the need for Python for loops.

In [1]:
import numpy as np

# Array creation

## Conversion from other Python structures

    Lists and tuples are defined using [...] and (...), respectively.
    
    Can define ndarry creation.

In [2]:
array_1D = np.array([1, 2, 3, 4])

print(array_1D)

[1 2 3 4]


In [3]:
array_2D = np.array([[1, 2], [3, 4]])

print(array_2D)

[[1 2]
 [3 4]]


In [4]:
array_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


    When you use 'numpy.array' to define a new array, you should consider the dtype of the elements in the array, which can be specified explicitly. 

## In-Built NumPy array creation functions

    numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)

In [ ]:
# 1D arrays


In [ ]:
# 2D arrays

In [ ]:
# ndarrays

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])