## Vectors & Matrices

    Matrix is a rectangular array of numbers, symbols, points, or characters each belonging to a specific row and column.
    
    Order : rows ⨯ and columns
    Denoted : [P]m⨯n where P -> matrix, m -> rows, n -> columns

### Operation on Matrices

In [3]:
# Addition of Matrices

import numpy as np

# Define the two matrices
matrix1 = np.array([[1, 2], [4, 5]])
matrix2 = np.array([[2, 3], [6, 7]])

# Calculate the sum of the matrices
result_matrix = matrix1 + matrix2

# Print the result
print(result_matrix)

[[ 3  5]
 [10 12]]


In [4]:
# Subtraction of Matrices

matrix1 = np.array([[1, 2], [4, 5]])
matrix2 = np.array([[2, 3], [6, 7]])

# Calculate the sum of the matrices
result_matrix = matrix1 - matrix2

# Print the result
print(result_matrix)

[[-1 -1]
 [-2 -2]]


In [5]:
# Scalar Multiplication of Matrices

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Define a scalar
scalar = 2

# Perform scalar multiplication using the * operator
result_matrix = scalar * matrix

# Print the result
print(result_matrix)

[[2 4]
 [6 8]]


In [8]:
# Multiplication of Matrices

# Define matrix A
A = np.array([[1, 2], [3, 4]])

# Define matrix B
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot()
result_matrix = np.dot(A, B)

# Print the result
print(result_matrix)

print("A @ B : \n", A @ B)

[[19 22]
 [43 50]]
A @ B : 
 [[19 22]
 [43 50]]


    Properties of Matrix Addition and Multiplication
        The properties followed by Multiplication and Addition of Matrices is listed below:

        (A + B) = (B + A) (Commutative)
        (A + B) + C = A + (B + C) (Associative)
        (AB) ≠ (BA) (Not Commutative)
        (AB) C = A (BC) (Associative)
        (A (B+C)) = (AB + AC) (Distributive)

In [9]:
# Transpose of Matrix

# Define matrix A
A = np.array([[1, 2], [3, 4]])

print('Before transpose : \n',A)

# Find the transpose of A using the .T attribute
A_transpose = A.T

print('After transpose : \n',A_transpose)

Before transpose : 
 [[1 2]
 [3 4]]
After transpose : 
 [[1 3]
 [2 4]]


    Properties of the Transpose of a Matrix

        The properties of the transpose of a matrix are mentioned below:

        (AT)T = A
        (A+B)T = AT + BT
        (AB)T = BTAT

In [10]:
# Trace of Matrix

# Define a square matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the trace of A using np.trace()
trace_A = np.trace(A)

# Print the result
print(trace_A)# 1+5+9 = 15

15


    Determinant of a Matrix
    
    A =  [[a b]
          [c d]]

    Then, the determinant is of A is |A| = ad – bc

In [12]:
# Define a square matrix A
A = np.array([[1, 2],
              [3, 4]])

# Calculate the determinant of A using np.linalg.det()
determinant_A = np.linalg.det(A)

# Print the result
print(determinant_A)

-2.0000000000000004


             [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

In [14]:
# Cofactor of Matrix

In [13]:
# Adjoint of a Matrix

# Define a square matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the cofactor matrix
cofactor_matrix = np.linalg.inv(A).T * np.linalg.det(A)

# Find the adjoint by transposing the cofactor matrix
adjoint_A = cofactor_matrix.T

# Print the result
print(adjoint_A)

[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


    Properties of Adjoint of Matrix
    The properties of the Adjoint of a matrix are mentioned below:

    A(Adj A) = (Adj A) A = |A| In
    Adj(AB) = (Adj B) . (Adj A)
    |Adj A| = |A|n-1
    Adj(kA) = kn-1 Adj(A)
    |adj(adj(A))| = |A| ^ (n-1) ^ 2 
    adj(adj(A)) = |A|(n-2) × A
    If A = [L,M,N] then adj(A) = [MN, LN, LM]
    adj(I) = I {where I is Identity Matrix}

In [15]:
# Inverse of a Matrix

# Define a square matrix A
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Calculate the inverse of A using np.linalg.inv()
inverse_A = np.linalg.inv(A)

# Print the result
print(inverse_A)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


    A^-1 = adj(A)/det(A)
    
    Properties Inverse of Matrix
    (A-1)-1 = A 
    (AB)-1 = B-1A-1 
    only a non-singular square matrix can have an inverse. 